apiVersion: v1
kind: Namespace
metadata:
  name: prep

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prep
type: Opaque
stringData:
  POSTGRES_PASSWORD: admin123
  POSTGRES_USER: admin
  POSTGRES_DB: testdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-no-persist
  namespace: prep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-no-persist
  template:
    metadata:
      labels:
        app: postgres-no-persist
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-no-persist
  namespace: prep
spec:
  selector:
    app: postgres-no-persist
  ports:
    - port: 5432
      targetPort: 5432
